In [1]:
import pandas as pd
import os

In [30]:
dataset = pd.DataFrame()

tokens = []
project_names = []
flakiness = []

projects = os.listdir('msr/flaky')
for project in projects:
    project_path = f'msr/flaky/{project}'
    files_per_project = os.listdir(project_path)
    
    for file_name in files_per_project:
        with open(project_path + '/' +  file_name, 'r') as reader:
            tokens.append(reader.read().replace("\n"," "))
            project_names.append(project)
    

dataset['token'] = tokens
dataset['project'] = project_names
dataset['flaky'] = 1

In [33]:
dataset

                                                  token   project  flaky
0     date LOCAL_ONE  Given simple 0 AM SELECT * FRO...  achilles      1
1     scriptExecutor session  Given simple crud  Whe...  achilles      1
2     child_value scriptExecutor session  Given simp...  achilles      1
3     SELECT child_value FROM entity_child WHERE id ...  achilles      1
4     child_value session  Given insert crud  When i...  achilles      1
...                                                 ...       ...    ...
1399  innerFilter Context shouldNotLeakContextForNes...     wroj4      1
1400  parallel took: {}ms LOG setParallelProcessing ...     wroj4      1
1401  r2 getLastTaskTimeMillis setParallelPreprocess...     wroj4      1
1402  Context getClass getResource css testFolder te...     wroj4      1
1403  encode ISO-8859-1 data BarcodeFormat StandardC...     zxing      1

[1404 rows x 3 columns]

In [37]:
dataset2 = pd.DataFrame()
tokens = []
project_names = []
flakiness = []

projects = os.listdir('msr/non_flaky')
for project in projects:
    project_path = f'msr/non_flaky/{project}'
    files_per_project = os.listdir(project_path)
    
    for file_name in files_per_project:
        with open(project_path + '/' +  file_name, 'r', encoding='ANSI') as reader:
            tokens.append(reader.read().replace("\n"," "))
            project_names.append(project)
    
dataset2['token'] = tokens
dataset2['project'] = project_names
dataset2['flaky'] = 0

In [38]:
dataset2

                                                  token project  flaky
0     testClassLoader other assertTrue conf getClass...  hadoop      0
1     this  contains a comment testCommentsInValue m...  hadoop      0
2     prefix declareProperty conf run String out CON...  hadoop      0
3     setDouble configuration DOUBLE_DELTA getDouble...  hadoop      0
4     value5 fileResource1 getResource Configuration...  hadoop      0
...                                                 ...     ...    ...
1397   0 1 0  set testToString array  1 0 1  expecte...   zxing      0
1398  getVersionForNumber <<  >>  testToString2 matr...   zxing      0
1399  bigEnough encode strangeWidth BarcodeFormat as...   zxing      0
1400  filter testNoRemoteHost 1.1.1.1 testRequest de...   zxing      0
1401  testDoS A B C  After one interval, should stil...   zxing      0

[1402 rows x 3 columns]

In [41]:
final = dataset.append(dataset2)

In [43]:
data = final.sample(frac=1).reset_index(drop=True)

In [46]:
data.to_csv('msr/msr_data.csv', index=False)

In [48]:
dataset2 = pd.DataFrame()

tokens = []
project_names = []

projects = os.listdir('new/flaky')
for project in projects:
    project_path = f'new/flaky/{project}'
    files_per_project = os.listdir(project_path)
    
    for file_name in files_per_project:
        with open(project_path + '/' +  file_name, 'r') as reader:
            tokens.append(reader.read().replace("\n"," "))
            project_names.append(project)
    

dataset2['token'] = tokens
dataset2['project'] = project_names
dataset2['flaky'] = 1

In [49]:
dataset2

                                                 token   project  flaky
0    rs ONE description wrapper when getQueryTrace ...  achilles      1
1    isNotNull withTtl RandomUtils manager nextInt ...  achilles      1
2    isNotNull withTtl RandomUtils manager nextInt ...  achilles      1
3    buid isNotNull actual manager assertThat Compl...  achilles      1
4    createTimerJobQuery getTime waitForJobExecutor...  activiti      1
..                                                 ...       ...    ...
811  http://www.google.com locate testValidUrl victim      wroj4      1
812  add callables debug submit LOG start delta Sys...     wroj4      1
813  add callables debug submit LOG overhead start ...     wroj4      1
814  encode ISO-8859-1 data BarcodeFormat expectedM...     zxing      1
815  random MAX_ERRORS fail getRandom corrupt Shoul...     zxing      1

[816 rows x 3 columns]

In [51]:
dataset3 = pd.DataFrame()
tokens = []
project_names = []

projects = os.listdir('new/non_flaky')
for project in projects:
    project_path = f'new/non_flaky/{project}'
    files_per_project = os.listdir(project_path)
    
    for file_name in files_per_project:
        with open(project_path + '/' +  file_name, 'r', encoding='ANSI') as reader:
            tokens.append(reader.read().replace("\n"," "))
            project_names.append(project)
    
dataset3['token'] = tokens
dataset3['project'] = project_names
dataset3['flaky'] = 0

In [52]:
dataset3

                                                 token   project  flaky
0    exception expect cluster should_exception_when...  achilles      0
1    cluster actual session KEYSPACE_NAME extractor...  achilles      0
2    isNotNull BEAN_VALIDATION_ENABLE initValidator...  achilles      0
3    initObjectMapperFactory ALL getInsertStrategy ...  achilles      0
4    given myConnector BpmnXMLConstants getAttribut...  activiti      0
..                                                 ...       ...    ...
811  decorate cannotDecorateNullObject DefaultSynch...     wroj4      0
812  decorate shouldDecorateCacheStrategy original ...     wroj4      0
813  never shouldNotCheckForChangesWhenResourceWatc...     wroj4      0
814          testBlackBoxCountingResults testBlackBox      zxing      0
815          testBlackBoxCountingResults testBlackBox      zxing      0

[816 rows x 3 columns]

In [54]:
merge = dataset2.append(dataset3)

In [56]:
new_final = merge.sample(frac=1).reset_index(drop=True)

In [58]:
new_final.to_csv('new/new_data.csv', index=False)